# -*- coding: utf-8 -*-
"""streamlit_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JICoptsWt1JNkqqQ6aCKkwGIBLIOWxbj
"""

import streamlit as st

st.write("hello world!")